<sv-page label="v3 — the project moves in" category="plan" order="1">

<sv-prose id="intro">
# v3 — the project moves in

v2 closed its own loop and shipped as 0.2.0 (2026-08-09). v3 was curated the same day, through the machinery v2 built: everything ever discussed sits in the pool (IDEAS.sv); what earned its place is the In list below. **Scope settled by the author, 2026-08-09 (thread 33: "that is enough for v3").** Rationale stays in the design docs; this page holds only what v3 commits to.

Carried principles, not up for re-decision: sv files are canon, the db holds what should not be versioned · the page file has one author, everything multi-writer goes through SQLite · reference, never embed · dogfood first.
</sv-prose>

<sv-prose id="in">
## In

- **Comment attachments** — paste/drop **any file** into the compose card, images first-class (author widened it from images, 2026-08-09); the daemon writes a project file, the comment references it, the agent reads it with its own tools. Design in the attachments section below. Arrives with a **comment-card redesign**: cards sized to carry media, not just sentences. *(pulled 2026-08-09; rationale in V2.sv's candidates)*
- **Resizable side rails** — drag-to-resize the contents rail and the comment bar, widths remembered as viewer preference; the expandable bar the image cards need, so it ships with them. *(pulled 2026-08-09, thread 28)*
- **A data table block — the plan** — settled 2026-08-10 in the plugins section: **the block is the big-table case only.** A few dozen rows are not a feature — an agent pipes a markdown table from whatever CLI it has into a prose block. Past a screenful it is a widget: fixed header, windowed *rendering*, resizable columns, sort — all client-side over a result streamed to the browser once, with the relay and a small run-and-stream contract ours while **the grid and engine are sqlnow's**, which embeds its engine and needs no duckdb binary present. No native grid is vendored, so neither VTable nor S2 is needed. *(pulled 2026-08-09, thread 29)*
- **Plugins — designed, then built** — design 2026-08-10 in the plugins section below; **the mechanism shipped 2026-08-15**: manifests + install list, `frame` mode served with its injections (`<base>`, `SIDEVIEW_BLOCK`, the two-function API, live theme), `call_cli`/`call_cli_streaming` execing the manifest's binary under the caps with abort-kills-child, same-origin parent measuring. Two working references in-repo — `extensions/duckdb` (streaming exec into a Vue grid) and `extensions/git` (the generality check) — live on the *Extensions demo* page; EXTENSIONS.md updated to as-built. `inline`/`sandbox` and the comment API remain design. *(pulled 2026-08-09, thread 30)*
- **html blocks as Vue islands — lean in** — the vendoring and CORS shipped in v2; v3 delivered the rest of the prize (2026-08-10, thread 39): an **import map in the iframe prelude**, so a block writes `import { createApp, ref } from 'vue'` — the spelling every model knows — instead of a vendored path it must be told; the skill teaches the pattern with its caveats (composition API with explicit `setup()`, no `<script setup>` sugar without a compiler; islands cannot reach the page); and `examples/vue-island.sv` is the worked example, live and interactive. *(pulled 2026-08-09, thread 31)*
- **Binary releases + AUR** — tag-triggered GitHub releases with prebuilt per-target archives, checksums and deb/rpm (the sqlnow shape — its release.yml is the template; sideview is pure Rust with embedded assets, so it can go simpler, and musl/static is on the table since nothing dlopens), plus an AUR package. `cargo install` stops being the only door. *(author, 2026-08-09, chat)*
- **Three page formats, and a repo config** — `.md` and `.html` become page formats sideview accepts and tracks, not new block types (author, 2026-08-10). Design in the formats section below; it replaces the md→sv conversion, so the docs stay markdown and GitHub keeps rendering them.
- **Page management at scale** — a project with many pages outgrows the chip strip: each `<sv-page>` may declare a `category` (canon, beside `order` — for committed pages, grouping is plan-worthy so it lives in the file), imported pages get theirs from `.sideview.toml`, and **the strip carries one category's pages and nothing else** (author, 2026-08-10). Its length is the whole point: a project may hold dozens of pages, but you work inside one set at a time, so the strip shows that set behind a title naming it — never a category chip, since listing categories in the strip is the length problem again. The title names the set and nothing more. The wordmark opens **`/home`** — every category with its pages, the untitled set leading — and that is the *only* place categories are browsed: per-category pages were built, tried and scrapped the same day. A project with no categories never sees any of it: home is then the view that existed before them, every page in the strip. **Built and dogfooded 2026-08-10**: this project's own eleven pages now live in four categories, its docs still markdown. *(pulled 2026-08-09, thread 32)*
</sv-prose>

<sv-prose id="goal">
## Comment attachments — the little plan

- **Any file, not just images** (author, 2026-08-09): the mechanics never cared — paste or drop into the compose card, the daemon writes the file, the comment references it. Images are the first-class case: thumbnail in the card, full size on click. Everything else wears a file chip — name, size, type — opening through `/f/`.
- **Three homes, split by lifetime — the placement principle applied to files** (author, 2026-08-09). *Comment* attachments live in `.sideview/attachments/<sha8>/<original-name>` — project-local (the sandbox law), self-gitignored, conversation's lifetime: if the db goes, they are fair game. A *throwaway page's* images live beside their page, `.sideview/pages/<session>/` — the page's lifetime: `page rm` takes the directory with the file, `page promote` moves it into the repo and re-points references. A *committed document's* files live in the repo proper, beside what references them, git's and untouchable — nothing that happens to the db or the conversation may ever threaten them. **The attachments folder takes writes from the comment upload alone** — a page's images never land there, whatever the page's tier; "add it to the document" copies *out* of conversation storage into the page's own home, the same crossing as promote.
- **The channel**: the page POSTs the raw bytes to a new `/api/attachments` (filename in the query — no multipart machinery to parse), which writes the file and returns its path and hash; sending the comment binds them as rows in an `attachments` table. **Metadata in the db, bytes on disk** (author, 2026-08-09): the card, the gc and "what references this" stay one query, while the file stays where every agent's own tools — including vision — read it directly. Blobs-in-db considered and rejected by the author the same day: they'd bloat the store, lengthen write transactions, and put an extraction step between the agent and the file. A canceled draft's upload is just an unreferenced file; gc collects it. An additive migration, priced with 0.3. Same trust line as comments: the page authors conversation, never canon.
- **Watch events name the paths.** The agent reads an image with its own file tool — genuine vision, pull not push, the founding thesis — and any other file the same way. The skill grows a line.
- **Lifecycle** (author, 2026-08-09): deletion follows the document — `page rm` cascades threads, comments, and their attachments with them. Everything else is a deliberate verb, never a daemon habit: `sideview attachments gc` deletes only files nothing references, checked against live conversation *and* every current page's content, and reports what it took (a startup auto-sweep was considered and dropped — after the resurrection test it would silently take everything). `--resolved` widens it to attachments held only by resolved threads, for repos where they pile up; explicitly not the default — resolved conversation is folded, not gone. **gc's writ runs only inside `.sideview/attachments/`** — committed document assets are git's, untouchable by construction; and a page found referencing conversation storage is protected but *reported* as mis-homed ("promote this file"), because the page-content check is a backstop for that mistake, not a place to keep canon.
- **Limits, honest and few**: a size cap, a sanitized filename, a sniffed content type. Nothing executes; `/f/`'s root confinement and its `.sideview` exclusions already apply.
- **Build order** (author, 2026-08-09): backend first — table, upload, gc, watch payloads — then the comment UI rebuilt around them; the card redesign and the resizable bar land as that one pass.
- **Inline placement, plain textarea** — paste/drop inserts a markdown-shaped token at the cursor (`![name](att:<sha8>)`); the card renders the thumbnail where the token sits; the watch body keeps the token, so the agent knows *which* image "this one" is when several ride one comment. Multiple attachments per comment stay allowed — a one-attachment cap was considered and declined (it scatters one thought across cards to solve an ambiguity the tokens already solve). No contentEditable, no rich-text editor.
- **Vim motions in the compose box** — an option, off by default, a viewer preference. The credible route is CodeMirror 6 vendored as a maintainer-built bundle (rung-1 precedent: maintainer-time toolchain, one-binary promise intact), vim keymap lazy-loaded. Priced honestly at a few hundred KB of vendor weight; decided at the *end* of the compose rebuild, when the textarea's limits are felt rather than guessed — it's an additive swap, not a foundation.
- Ships with the comment-card redesign and the resizable bar, per the In list.

**Migration v3** — the model, for review before a line is written:

```sql
CREATE TABLE attachments (
    id         INTEGER PRIMARY KEY,
    comment_id INTEGER NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
                                  -- rows are born when the comment is sent, never
                                  -- at upload: a canceled draft leaves only an
                                  -- unreferenced file for gc, not a dangling row
    path       TEXT NOT NULL,     -- project-relative: .sideview/attachments/<sha8>/<name>
    name       TEXT NOT NULL,     -- original filename, sanitized; kept for the agent's sake
    mime       TEXT NOT NULL,     -- sniffed at upload, never trusted from the client
    bytes      INTEGER NOT NULL,  -- the cap is enforced at upload, recorded here
    sha256     TEXT NOT NULL,     -- integrity and the dedupe key: same bytes, one file
    created_at INTEGER NOT NULL
);
CREATE INDEX attachments_by_comment ON attachments(comment_id);
CREATE INDEX attachments_by_sha    ON attachments(sha256);
-- the FK cascade clears rows when conversation goes (page rm); the daemon deletes
-- the files it queried first — SQL cannot unlink from disk, and gc backstops it.
-- Watch events carry the whole row (path, name, mime, bytes), not just a path.
```

## Three page formats, and `.sideview.toml`

- **Formats, not block types** (author, 2026-08-10). A page is a file; sideview knows three. `.sv` stays the *composed* format — typed blocks, interleaved diffs and (later) tables. `.md` and `.html` are *imported* formats: rendered whole, one block per file, through the paths that already exist. No format change, no new tag, no new thing for the skill to teach — the limitations attach to the format, where a reader looks for them.
- **What you get, stated plainly.** Markdown and inline HTML render into the page and are **fully commentable** — anchors are heading ids and paragraph hashes computed from the *rendered* text, which never cared where the text came from. A full HTML document that wants its own world is iframed instead, and there commenting stops at the block: the page cannot reach into a sandboxed frame (V0's rule, unchanged). Inline HTML runs its own CSS and JS in our page — the same trust story as markup blocks, and the same caveat: body-level layout will fight the chrome.
- **One block per file, deliberately.** Splitting a doc at its headings would give surgical patches but make block ids heading-derived — and block ids are what comments target, so renaming a heading would orphan every thread under it. One block keeps paragraph anchors surviving everything except an edit to their own paragraph; the whole-file re-render is absorbed by the reading anchor today and fixed properly by patch-in-place morphing later.
- **`.sideview.toml` at the repo root — TOML, committed, agent-authored** (author, 2026-08-10; no CLI writer, since agents edit files trivially and the one-author rule stays intact). Root, not inside `.sideview/`: that directory self-ignores with a single `*` and holds disposable machinery, while config is versioned intent — the placement principle, applied to a config file.
- **It supplies only what a file cannot say about itself.** An `.sv` page declares its own label, order and category in canon. Markdown and HTML have nowhere to put attributes, so config is their only voice: `[[pages]]` with `path`, `category`, optional `label`/`order`, and `render = "inline" | "iframe"` for HTML. Precedence follows: the file wins for anything it can express, config fills the rest.
- **Config is what survives the db.** Entries are re-applied at startup, so the resurrection test brings imported pages back too — `.sv` files announce themselves in the scan, markdown never does, and sideview must not colonize a repo's markdown by scanning for it. `port` joins it for the same reason: V2's own sign-off recorded that the remembered port dies with the db, and durability of that kind belongs in configuration.
- **Deletion splits by tier, not by format** (author, 2026-08-10, sharpening it): a throwaway page under `.sideview/pages/` is sideview's own scratch and `rm` means rm; **anything in the repo — a promoted `.sv` as much as an imported `DESIGN.md` — is unbound and left on disk**, because it is a committed file and should be exactly as scary to delete as any other. The page's ✕ never deletes canon; `page rm <id> --file` is the deliberate second word, and git is the other answer.
- **A bad config never costs you the page**: log it, report it in `status`, serve without it. And note for the docs: a worktree's store resolves to the main checkout, so the daemon reads that copy of the config.

## Plugins — the design

- **Registration is the trust act** (author, 2026-08-10, and the model is VS Code's, not the web's). An extension listed in config is an *install*: fully trusted, same-origin, may reach a CDN, may call the page's own endpoints. Agent-authored `sv-html` is *content*: `srcdoc`, sandboxed, envelope-only. Nobody has to reason case by case — you either installed it or you didn't. The `sandbox` attribute was never buying security for code you installed on purpose.
- **The type is the extension's declaration, never the installer's choice** (author, 2026-08-10, correcting the reverse). With trust settled, the mode decides only what the plugin's CSS and JS are *written against*, and only its author knows that: an inline plugin authored against Bootstrap and the tokens would look broken alone in a frame; a framed one with its own reset would trample the page. They are different artifacts, so the manifest says which.
  - **`inline`** — renders into the page; inherits Bootstrap, the tokens and the theme; **commentable with no new machinery**, since its text hashes like any other. Its CSS is global in both directions — the price of sharing the chrome. Relative asset references are rewritten to the plugin's own directory, because the manifest names it and `./style.css` should mean what the author obviously meant.
  - **`frame`** — its own CSS and JS in a same-origin iframe served from `/f/`: isolated *styling*, not isolated trust. The parent can measure it directly (no sizing handshake) and can walk its DOM, so **comments work here too**.
  - **`sandbox`** — **reserved, deliberately not built** (author, 2026-08-10): an opaque-origin frame for embedding a foreign app — an Observable widget, someone else's bundle — where the extension wants no access and is granted none. Space is left in the vocabulary because the machinery is already the content path; comments there would need the plugin to post `{sv: 1, type: "comment", …}` itself, which makes commenting a capability a plugin *offers* rather than one the host takes.
- **A plugin is a directory with a manifest.** `extensions/<name>/plugin.toml` — `name`, `type`, `entry`, `version` — beside its html, css, js and assets, served through `/f/` under the confinement that already exists. Required, not inferred from a stray `index.html`: the manifest is what makes an install deliberate, and it follows the standing rule that config supplies only what an artifact cannot say about itself.
- **`.sideview.toml` shrinks to an install list** — a path, whether it is enabled, and whatever the *project* decides that the plugin cannot.
- **Degradation is envelope-first**, as everywhere else: an unknown `type`, or a manifest `version` above what this daemon knows, renders an honest "this sideview doesn't know…" note rather than guessing.
- **The other plugin kinds, named and not built**: *block plugins* (a custom element claiming `sv-<tag>`, the daemon passing the body through instead of degrading it) · *subprocess plugins* (a command whose stdout is rendered — DESIGN.md's "a command, its streams, an optional port") · *chrome plugins* (rail lenses, header controls, the `window.sideview` API — the only kind that can break the page, and same-origin trust means it needs no `postMessage` plumbing when it comes).
- **First step, and only that**: HTML as a file in both built types, registered, with the commenting that falls out. Distribution from outside the repo — npm, crates, a URL, SRI — stays a separate decision.

**Binary extensions — the LSP-shaped route** (author, 2026-08-10; design only, a v3-plus-one build):

- **Two axes, not one** — the author's binary idea exposed a conflation in the types above: how a plugin's HTML is *produced* and how it is *hosted* are independent. The manifest wants `source = "file" | "command"` (later `"process"`) beside `render = "inline" | "frame" | "sandbox"`. A binary's output can be hosted any of the three ways.
- **The convention is sideview's own**: an extension declares a tag, a block reads `<sv-sqlnow>select … from readings</sv-sqlnow>`, and the daemon runs the binary with **the body on stdin** and attributes as flags — no argument quoting to get wrong. stdout is the block. This is a better *first* block plugin than the custom-element sketch, because rendering stays server-side where all other rendering lives, and it is `{sql}` finally exercising reference-never-embed: the spec holds a query, the rows reach the page without passing through any model's context.
- **Four rungs, and the second is the interesting one.** (1) *Exec per render* — block changes, run, done; enough for a table in a plan. (2) **Streaming exec** — the author's instinct, and simpler than it sounds rather than harder: the same one-shot child, its stdout consumed as it arrives, ending when the process does. In `frame`/`sandbox` mode this is **free and needs no protocol at all** — the daemon serves `/x/<ext>` as a chunked response and the browser paints rows as they stream, which is how HTML worked before anyone invented a client; inline mode has no such luxury and would need an append event kind. (3) *Exec per request* — the page POSTs arguments to `/x/<ext>` for sort, page, drill; that endpoint exists already for rung 2. (4) *A persistent stdio child* speaking JSON lines — LSP proper, for a warm connection across many queries.
- **Startup cost is priced and accepted** (author, 2026-08-10): a Rust binary starts in nothing, and while DuckDB opening a database and loading extensions is real, nobody is waiting on it — you have been waiting on the model far longer. So rung 4 exists for *repeated queries over a warm connection*, never for latency, which reorders the ladder honestly.
- **Caps and honesty, specified rather than discovered**: a timeout and an output-size cap (a runaway query must not hang the poll loop or push half a gigabyte into a page), stderr to `daemon.log` with a visible error block on non-zero exit rather than a silent gap, cwd at the project root, and a re-run policy that is *never* every poll tick — re-run on a change to the block's body or attributes, plus an explicit refresh and any input globs the extension declares.
- **Engine and view are separable, which is what settled the table** (author, 2026-08-10): a binary or child process is an *engine*, a page or island is a *view*, and they meet at `/x/<ext>`. That is why nothing needs forking — sqlnow can supply both sides while sideview supplies neither, and any other engine can take the same place later.
- **Two manifest fields**: `output = "html" | "markdown"` — a binary that already speaks markdown should not have to learn HTML, and markdown lands in the path comrak and the prose layer already own — and **argv templating from block attributes**, `args = ["--rpc", "{db}"]`, run as an argv array with **no shell**, each placeholder becoming exactly one argument. Same lesson as choosing gitoxide over `git`: never build a command line out of strings someone else can influence.
- **Measured while considering a duckdb-CLI table and kept as general guidance** (2026-08-10; the CLI route itself is *not* taken — see the table entry): a binary's *aligned* output buffers by construction (duckdb's `-markdown` took 1.6s to first byte on 5M rows, since column widths need the whole result) while its *line-oriented* output streams from the first millisecond (`-jsonlines`, `-csv`: 11ms). Process start is a non-issue — 11ms cold, 37ms for a million-row aggregate. So an extension that must stream should emit lines, and one that must align should not pretend to stream.
- **The table extension is the big case only** (author, 2026-08-10). A few dozen rows are not a feature: an agent runs whatever tool it has — sqlnow's CLI, duckdb's, anything — and pipes a markdown table into a prose block, which works today and adds no dependency to anything. **Anything bigger than the screen is a widget, not a rendering**: fixed header, windowed rendering (paint what is visible, not 50,000 rows of DOM), resizable columns, client-side sort. So the extension targets that and only that, and **it does not depend on the duckdb binary** — sqlnow embeds its engine, which was part of its own design.
- **The data goes to the browser, and scrolling is not a request** (author, 2026-08-11, correcting the note this bullet used to carry). A result is transferred in bulk — streamed as lines, ending when the child does — and the grid then virtualizes, sorts and resizes **locally**: it paints what is visible out of rows it already holds. A request happens per *query*, not per scroll. So the mechanism a table needs first is the streaming exec of rung 2, not a windowed protocol.
- **The channel is ours; the grid and the engine are sqlnow's.** A `frame`-mode extension serves sqlnow's own UI from its own files, and that frame — same-origin — fetches `/x/<ext>`, which the daemon **relays** to the child over pipes. What sideview owns is the relay and a deliberately small contract — *run this, stream me the result* — and no grid at all, which is how a properly-considered table widget gets built without us building it. Kept general because sqlnow is the first implementation, never the definition; the wire format between them (json lines, arrow, whatever) is sqlnow's business, since it owns both ends.
- **Child lifecycle**: spawned on first request, **one per block** (each holds its own connection), kept while a viewer is attached, reaped after idle, killed with the daemon — which is the reaping DESIGN.md already promised, arriving through pipes instead of ports.
- **Windowed reads are a later, larger case** — a table too big to hand the browser at all, where the grid would ask for *rows 5,000–5,100 sorted by column three* with ids and cancellation, LSP-shaped. Explicitly not the first target: sqlnow does not support it today, and designing around it would buy latency nobody is paying. A warm child earns its place for **repeated queries**, not for scrolling.
**The table, shortest path — sqlnow in a subprocess, iframed** (author, 2026-08-13, deliberately setting aside every "always available / default / integrated" requirement above; those stand for the long run). The reason is sqlnow's **formatted cells** — diffs and graphs rendered inside cells — a key feature nobody wants to reproduce here.

- **Measured before designing** (2026-08-13): sqlnow sets no `X-Frame-Options` and no CSP, so **it iframes**; first page served **1.5s** after spawn; and a second child over the *same inputs* **refuses** — the session is derived from its inputs and the single-writer guard fires (`--no-register` does not help).
- **So: one child per input set, one seeded query per block.** `sqlnow --port <free> --host 127.0.0.1 -q "<blockid>=<sql>" … <inputs>`, and each block's iframe deep-links to `/queries/<blockid>` — verified serving. Blocks sharing a database share a child and its warm connection.
- **An isolated store per child**, `XDG_CONFIG_HOME` under `.sideview/` — verified to defeat the guard, and it stops sideview's block queries being written into the user's real sqlnow sessions (observed: a stale query from an earlier run reappeared, because same inputs mean same session).
- **The iframe is proxied through the daemon** (`/x/table/<key>/*`), never an absolute `host:port`. Over the tailnet — the normal case — `127.0.0.1` in an iframe is the *viewer's* localhost, and the alternative is binding sqlnow to `0.0.0.0`, which V0 names the one clearly wrong answer. Proxying also keeps it same-origin, which leaves comments possible later rather than impossible forever.
- **Path proxying is not transparent, measured 2026-08-14**: sqlnow's UI is entirely root-absolute — `/assets/*`, `/query.json`, `/api/events`, `/api/queries`, `/tables.json`, `/outputs`, and the router's own `/queries/…`. Behind `/x/table/<key>/` the document serves and everything it asks for then escapes the prefix into sideview's root. So there are two roads: **port proxying** (sideview binds an extra port per child and forwards blindly — needs nothing from sqlnow, costs a port per table on the tailnet and an `ssh -L` each), or **sqlnow learns a base path**, which is preferred and is four small things: Vite `base: './'`, `<base href="{BASE}">` injected into index.html by the same patching that already writes `window.SQLNOW_SCOPE`, a `window.SQLNOW_BASE` used for `fetch` and as React Router's `basename`, and BASE read from the **`X-Forwarded-Prefix`** header so no flag or restart is involved and an absent header means today's behaviour. One collision solved for free by work already done: path proxying puts every child on one origin, where their `localStorage` would clash — except keys are already namespaced by `SQLNOW_SCOPE`.
- **The proxy itself is unremarkable**: strip the prefix, forward method, headers and body with `awc`, stream the response back so `/api/events` is not buffered, 502 honestly while a child is still starting.
- **Communication is spawn arguments and nothing else** (author): no protocol, no stdio, no envelope. A block changing its SQL respawns its child; the block spec holds a path and a query, so reference-never-embed holds.
- **What it honestly is not**: not commentable inside (cross-document today), not sized by the envelope (a grid wants a declared height), not available without the sqlnow binary — degrading with an honest "sqlnow not found" note. Lifecycle as designed: reaped on idle, killed with the daemon.
- **Sandbox-wise it is sound** (author): the *daemon* spawns the child and the daemon is unsandboxed by design, started by hand. No agent ever spawns a server.
- This is the extension design's first resident, expressed as core for now; re-expressing it as `source = "process"`, `render = "frame"` is the tidy-up, not the feature.

**Exec-per-request, surveyed and vindicated** (author's original design, reinstated 2026-08-14 after the proxy survey soured every resident-server route; then measured). One-shot exec answers a query over a million-row DuckDB file in **~30ms** (server spawn to first answer: ~500ms warm, 1.5s cold) — and a survey of every request sqlnow's UI makes found **nothing too hot for a 30ms exec**: `/query.json` fires per explicit Run, the sidebar fetches per navigation, the worst case is a 500ms-debounced autosave while typing SQL (hidden anyway in `frame=query` mode), and there is no per-keystroke call, no autocomplete, no polling. The one structural exception is the SSE stream at `/api/events` — a held connection cannot be an exec — and it is inessential embedded: its only job is sidebar sync between writers, which is sideview's job here; drop it in frame mode or serve a no-op. **This is rung 3 of the binary-extension ladder arriving as the table's architecture**: the static shell pre-rendered and served by sideview, every dynamic request an exec, CGI-shaped — no resident child, no port, and the proxy-prefix problem never exists because the frame's requests go to sideview's own origin. Two small sqlnow gaps: one-shot accepts only a DuckDB file today (no `sqlnow sql data.csv`; the inputs-replay machinery exists in `query_database`), and it needs a `respond <path>` entry point — body on stdin, response on stdout — dispatching to the handlers the server already uses.

**Why CGI's reputation does not transfer here** (author, 2026-08-15, closing the question "is this good enough"): CGI fell out of fashion for two reasons, and neither applies. *Slow-starting dynamic languages* — this is a compiled binary, and the 30ms measurement already includes opening the DuckDB file, which is the modern name for the per-request database connection CGI was famous for draining. *High concurrency* — a sideview page has a handful of viewers at most, and would still if a collaborative version ever shipped; exec-per-request drains resources at thousands of requests per second, not at human-paced clicks from a few users. Two rules keep the pattern from eroding as it spreads to other plugins:

- **The statelessness contract, stated rather than observed**: a `respond` handler must assume a fresh process per request — the session file and inputs are the only memory. Today's survey found nothing in sqlnow that assumes otherwise; this sentence is what keeps that true on purpose when future features (a prepared temp table, a cached fetch) would otherwise break it silently. Concurrent sidecar writes ride sqlnow's existing lock-retry; test once rather than trust.
- **The ladder rule — argue your way out, never in**: static file → exec per request → resident process, each step taken only on a demonstrated failure of the previous. What qualifies: a held connection (SSE, websockets, a PTY), state genuinely expensive to rebuild (an LSP's index — DuckDB at 30ms is the counterexample), or push rather than pull. Streaming does *not* qualify — a chunked exec response streams fine. Any plugin claiming rung 4 gets the same suspicion exec-per-request just survived.

- **The mechanism is documented as a contract: [EXTENSIONS.md]** (2026-08-15, registered as a live page under *design*) — written to stand alone, so an agent in another repo can build an extension against it with none of this page's history; the author's test of the mechanism's clarity is exactly that agent succeeding or failing. It is honest that the mechanism is specified, not yet built, and it firms three things the bullets here left loose: the tag claim (`name` claims `<sv-name>`), the reserved `height` attribute versus measured sizing, and the injected live `data-bs-theme`.
- **The frame calls its binary through a two-function JS API** (author, 2026-08-15, replacing a rejected alternative recorded below): sideview injects `sideview.call_cli(args, {stdin})` → `{code, stdout, stderr}` and `sideview.call_cli_streaming(args, {stdin})` → the stdout stream, into a registered extension's frame at serve time — the same injection that writes `<base href>` — plus `window.SIDEVIEW_BLOCK = {id, attrs, body}` so the frame knows its SQL and inputs without asking. Each call is one POST to `/x/<key>/call`; streaming is a chunked read, and **aborting the fetch kills the child** — cancellation for free. The daemon execs only the binary the manifest names, argv array, no shell: the plugin chooses arguments, never the executable. Big payloads ride stdin. The caps apply; non-zero exit is a 500 carrying stderr, with the honest streaming caveat that a failure after the first chunk can only truncate and log. The endpoint exists only under a registered key, and `/x/` sends no CORS header, so opaque-origin content islands cannot reach it — content stays content.
- **Why this beat the URL-emulating dispatch** (rejected 2026-08-15, the author's words: clever but surprising, and potentially inflexible): CGI-style path dispatch quietly re-imposes "pretend to be a web server" on a binary whose appeal is that it isn't one — sqlnow would have grown a `respond` shim mapping paths to handlers when its existing CLI verbs (`sql --format jsonl`) already answer; the protocol belongs to the plugin, and sideview should have no opinion about what a binary's output means. The move deletes the dispatch table, the header-preamble conventions and the SSE no-op in one stroke. What survives from that analysis: Vite `base: './'` (the shell's assets still load from the frame's path) and the one-shot-over-CSV gap, now load-bearing since the one-shot verbs *are* the interface.

**Why CGI's reputation does not transfer here** (author, 2026-08-15, closing the question "is this good enough"): CGI fell out of fashion for two reasons, and neither applies. *Slow-starting dynamic languages* — this is a compiled binary, and the 30ms measurement already includes opening the DuckDB file, which is the modern name for the per-request database connection CGI was famous for draining. *High concurrency* — a sideview page has a handful of viewers at most, and would still if a collaborative version ever shipped; exec-per-request drains resources at thousands of requests per second, not at human-paced clicks from a few users. Two rules keep the pattern from eroding as it spreads to other plugins:

- **The statelessness contract, stated rather than observed**: a `respond` handler must assume a fresh process per request — the session file and inputs are the only memory. Today's survey found nothing in sqlnow that assumes otherwise; this sentence is what keeps that true on purpose when future features (a prepared temp table, a cached fetch) would otherwise break it silently. Concurrent sidecar writes ride sqlnow's existing lock-retry; test once rather than trust.
- **The ladder rule — argue your way out, never in**: static file → exec per request → resident process, each step taken only on a demonstrated failure of the previous. What qualifies: a held connection (SSE, websockets, a PTY), state genuinely expensive to rebuild (an LSP's index — DuckDB at 30ms is the counterexample), or push rather than pull. Streaming does *not* qualify — a chunked exec response streams fine. Any plugin claiming rung 4 gets the same suspicion exec-per-request just survived.

- **The request path, concretely** (author's question, 2026-08-15: is there a sideview API to call?). **No JS API — plain HTTP to one generic route.** The frame is served from `/x/<ext>/<key>/` on sideview's origin, so the UI's own `fetch("query.json")` lands at `/x/<ext>/<key>/query.json`; the daemon dispatches by tail: static tails serve the extension's files with no exec, dynamic tails exec the manifest's `respond` command with CGI's conventions (method and query as args/env, body on stdin, status + headers + body on stdout), and `api/events` is answered by sideview itself as a keepalive no-op, since an exec cannot hold a connection and embedded it has nothing to say. `<key>` resolves to the block's spec and fills the argv template, so every exec knows which store and inputs it answers for. The one surviving piece of the proxy problem: sqlnow's bundle calls `location.origin + "/query.json"` today, so it still needs base-relative URLs (`window.SQLNOW_BASE`) — simplified though, because sideview serves the shell and injects `<base href>` and the global itself; no `X-Forwarded-Prefix` dance. `window.sideview` stays reserved for chrome plugins; the table needs no JS API at all.

**What sqlnow implements for this — the author starts there** (2026-08-13, since he controls its release):

- **Framing modes ride the URL, not the process**: `?frame=full|queries|query` on any route, so one child serves a full UI to one block and a bare grid to another with no respawn and no per-child state, composing with the verified deep links (`/queries/b1?frame=query`). `full` is today; `queries` keeps the saved-query switcher and drops the tables list; `query` is grid only.
- **`query` mode hides the editor, for an architectural reason rather than a cosmetic one**: the block file owns the SQL, so an editable box in the frame invites divergence between what the page says and what the grid shows. An "open in sqlnow" link pops the full UI in a new tab — explore there, canon stays in the page.
- **Sizing and theme are the existing envelope**, nothing new invented: child → parent `{sv: 1, type: "size", height}` on load and on resize; parent → child `{sv: 1, type: "theme", mode}`. The theme leg is the bigger win — a grid in the page's own palette stops reading as a foreign app.
- **Block-level comments come first, and cells may never come at all** (author, 2026-08-13): the clear way to ask about a table is to comment on **the block as a whole**, and per-cell threads bring an orphaning problem that outweighs their value. Built the same day: a bubble in the top-right corner starts a thread at the block's tail — which until now was unreachable, since every gesture went through a text selection and an iframe has no text to select. It is also the simplest thread in the system: an empty anchor never orphans, outliving every edit to the block's content and dying only with the block. **It appears only on blocks with no selectable text** (author, same day, having seen it everywhere): elsewhere selection already works, and a second affordance would make the reader reason about a block-type divide they should never have to see. Where it does appear it stays quietly visible rather than hover-revealed, since those blocks offer no other gesture — on touch least of all.
- **Cell comments, when they come, arrive through the extension API, not postMessage** (author, 2026-08-15: `create_comment` opening a pre-anchored draft in the bar, `get_comments`/`on_comments` for highlighting, jump delegated inward, orphaning the extension's business — specced in EXTENSIONS.md, lands after the first build; the `{sv:1,type:"comment"}` envelope stays for the sandbox tier). The canvas fact below still stands — the host can never scrape a grid: **cell comments, if ever, must come from sqlnow, not from us** — measured consequence: glide-data-grid draws on **canvas**, so there is no DOM text in the frame for the host to select or hash, however same-origin the proxy makes it. So this is the reserved third tier arriving for real: the app *offers* commenting by posting `{sv: 1, type: "comment", anchor, quote, context}`, with the quote human-meaningful (column, row, value, query name). We add a `c:` form beside `h:`/`p:`/`l:`; positional anchors orphan when the query changes, and the quote captured at creation is what preserves meaning, exactly as elsewhere.
- **Three asks that let sideview stop being clever**: an explicit store isolation flag (`--store <dir>` or `SQLNOW_STORE`) so we need not fake `XDG_CONFIG_HOME` to dodge the single-writer guard and to keep block queries out of real sessions · `--port 0` binding ephemeral and printing the chosen URL, so we read a line instead of racing to reserve a port · `prepare()`'s notes moved from stdout to stderr.

**The fallback retreats to a CSV viewer, and the engine goes entirely (author, 2026-08-16, after seeing the numbers: "I have turned a bit precious about compile time and binary size").** The default table runs no SQL at all: agents grab whatever tool they have — duckdb, sqlnow, sqlite3, pandas — and all of them emit CSV, so shipping a query engine solved a problem agents do not have. They have the rows; sideview needs only the *view*. Interactive querying was always sqlnow's job, and the duckdb extension covers the middle. This is the first position satisfying every constraint at once: zero binary growth, zero compile time, always available, reference-never-embed intact. Two shapes, the choice open:
  1. **Core `sv-csv`, server-rendered** (recommended): the block holds a path, the daemon parses (the tiny pure-Rust `csv` crate) and renders a real table through the pass everything else uses, row-capped with an honest "showing N of M". Buys what a JS grid cannot: commentable, snapshot-able, zero JS, styled by the prose layer. Fulfils two standing designs instead of inventing: V0's "the first block to actually test reference-never-embed is `table`" — arriving as CSV — and the `RootRelPath` newtype finally getting its user. The daemon statting the referenced file makes it live: overwrite the CSV, the block re-renders — DESIGN.md's sidecar sleeper waking in its simplest form.
  2. A pure-UI extension (no `bin`; the frame fetches `/f/<path>` and renders client-side) — dogfoods the mechanism, but costs comments, snapshots, and reopens the shipped-default install question for something with no weight left to justify it.
  Sort and resize deliberately miss this cut: wanting them means leaving "simple", and that is sqlnow's door.

**The fallback engine, measured and settled in shape (2026-08-16)** — the author's proposal: promote the grid, and make the always-present engine a *subcommand of sideview itself* consumed through the extension mechanism (`bin = "sideview"`), so "always available" is satisfied by the one binary guaranteed present, core still ships no table, and the shipped default is built on the same contract third parties get. Measured before choosing the engine inside it: DataFusion is **90 MB un-LTO'd but 35.1 MB under fat LTO** (opt-s, 5m06s build, 10ms cold query) versus duckdb-bundled's 41.6 MB — so the pure-Rust engine *is* the lighter fallback after all, and it is trivially static/musl-friendly where DuckDB's C++ is the release matrix's documented pain. Honest costs, on the record: not DuckDB's dialect, no `.duckdb` files — the fallback is vanilla SQL over parquet/CSV/JSON, and real databases stay the duckdb/sqlnow extensions' business. `sideview query --format jsonl|markdown` (SQL on stdin) also rescues the small-table story with zero external installs. Two riders: a reserved `bin = "sideview"` resolves to `current_exe()` so engine and daemon can never skew; and fat LTO's 90→35 finding argues for LTO in sideview's own release profile regardless — CI pays the link time, everyone downloads less. Open sub-question, deliberately the author's: how the shipped default extension installs — embedded-and-implicit (shipping in the binary is the trust act for first-party, config can disable) versus materialized into `extensions/` by a command (contract purity, one more step).

- **The always-available table: measured costs, 2026-08-11** (author's requirement: a table view that needs no external binary, with a real grid and decent DuckDB support). The two candidate approaches are not rivals — a datagrid is the *view*, an embedded engine is the *engine*, and this needs one of each.
  - **View: vendor VTable, do not write a grid.** It is a single UMD file, canvas-based, framework-neutral with an async data model — the 2026-08-08 verdict — and it obeys the no-build law. Hand-rolling fixed headers, windowed painting, resize and sort is a month of polish to arrive where it already is. (glide-data-grid's React-only disqualification stands for core and evaporates for an extension serving its own app.)
  - **Engine: in-process DuckDB, `bundled` only.** Measured on this machine: sideview today is **14.9 MB**; a hello-world plus `duckdb/bundled`, stripped, is **41.6 MB** built in **4m10s** — and that minimal build already reads parquet, CSV and JSON, *and* can `INSTALL`/`LOAD` httpfs, sqlite and postgres **at runtime** with no size cost. `extensions-full` (sqlnow's setting) adds ~20–25 MB and buys only *offline* availability, which the extension layer's own principle says extras need not have. So the honest price of an always-available table is roughly **15 → 55 MB** and four minutes on a fresh `cargo install` — most people never paying it once binary releases ship.
  - **Runtime installs land in `~/.duckdb/extensions/`**, which brushes nothing-under-`$HOME` — a rule that exists because the *sandbox* cannot write there, and the daemon is not sandboxed. `SET extension_directory` into `.sideview/` honours the spirit for one line.
  - **libsqlnow is still worth publishing rather than reimplementing**: the nested-type value formatting through Arrow's `ArrayFormatter`, the `LIMIT n+1` truncation probe, input replay (a CSV or parquet path becoming a view) and db sniffing are the subtly hard parts, and one implementation shared between two projects means a fix lands in both. The ask on it: features to drop actix, the UI and sessions — and to stop *forcing* `extensions-full`, or sideview inherits 25 MB it does not want. (Its embedded `static/` is 6.1 MB of which ~3.5 MB is stale duplicate Vite output; irrelevant to sideview, a free win for sqlnow's own release.)
  - **Rejected, with its reason**: a pure-Rust engine (DataFusion, Polars SQL) needs no C++ build and would stay near 30 MB, but cannot open a `.duckdb` file at all and is not DuckDB's dialect. Right only if the requirement were "good SQL over files" rather than DuckDB.
- **A quiet consequence**: a persistent stdio child *is* "supervise → endpoint" without ports or namespaces, since the daemon runs on the host and talks over pipes. The service-block thesis gets a first version that never needed the spike.

## The comment UI around attachments

- **Mobile: the open bar is the page** (author, 2026-08-09, from the phone: the bar is already as wide as it can realistically be — so stop pretending). Two states, folded-to-chip and full-screen sheet: the sheet covers the header and chip menu, the document beneath stops being drawn, the body is locked at its reading position, and a thumb-sized × in the title row is the way out. **Built and lived in the same day** — the seven platform causes it took are in HANDOFF, and its shape is now structural (title row above a scrolling sibling, sheet pinned to the *visual* viewport so the keyboard never buries the compose box). Desktop keeps the side bar, and drag-to-resize arrives with it.
- **Compose**: paste or drop into any compose box — draft or reply — uploads immediately and inserts the token at the cursor (`![name](att:<sha8>)`); a chip row under the box shows what rides the comment, with remove. Every upload attaches whether or not its token survives editing; tokens control *placement*, not membership.
- **Cards**: image tokens render as thumbnails where they sit, tap for full size through `/f/`; non-image attachments wear a file chip — name, size — tap to open. Attachments without a token trail the body.
- **Bodies graduated to markdown on day one** (author, 2026-08-09 — raw tokens sitting in sent cards made the case the plan predicted): rendered server-side by the same comrak pass as everything, in *safe* mode — raw HTML escaped, never omitted, because a comment comes from whoever can see the page — with `att:` images resolving against the comment's own rows. The compose box stays raw text, preview-on-send; inline WYSIWYG remains the CodeMirror question, decided at the end of this pass.

## Goal — blessed by the author, 2026-08-09 (thread 33)

v3 is done when every item on the In list above is accepted by the author — through this page's own machinery — and **0.3.0 is on crates.io**.
</sv-prose>

</sv-page>
