<sv-page label="v3 — the project moves in" category="plan" order="1">

<sv-prose id="intro">
# v3 — the project moves in

v2 closed its own loop and shipped as 0.2.0 (2026-08-09). v3 was curated the same day, through the machinery v2 built: everything ever discussed sits in the pool (IDEAS.sv); what earned its place is the In list below. **Scope settled by the author, 2026-08-09 (thread 33: "that is enough for v3").** Rationale stays in the design docs; this page holds only what v3 commits to.

Carried principles, not up for re-decision: sv files are canon, the db holds what should not be versioned · the page file has one author, everything multi-writer goes through SQLite · reference, never embed · dogfood first.
</sv-prose>

<sv-prose id="in">
## In

- **Comment attachments** — paste/drop **any file** into the compose card, images first-class (author widened it from images, 2026-08-09); the daemon writes a project file, the comment references it, the agent reads it with its own tools. Design in the attachments section below. Arrives with a **comment-card redesign**: cards sized to carry media, not just sentences. *(pulled 2026-08-09; rationale in V2.sv's candidates)*
- **Resizable side rails** — drag-to-resize the contents rail and the comment bar, widths remembered as viewer preference; the expandable bar the image cards need, so it ships with them. *(pulled 2026-08-09, thread 28)*
- **A data table block — the plan** — settled 2026-08-10 in the plugins section: **the block is the big-table case only.** A few dozen rows are not a feature — an agent pipes a markdown table from whatever CLI it has into a prose block. Past a screenful it is a widget: fixed header, windowed rendering, resizable columns, sort — reached over a **stdio protocol that is ours while the grid and engine are sqlnow's**, which embeds its engine and needs no duckdb binary present. No native grid is vendored, so neither VTable nor S2 is needed. *(pulled 2026-08-09, thread 29)*
- **Plugins — the design** — designed 2026-08-10, in the plugins section below: registration is the trust act, the extension declares its own type (`inline`, `frame`, and `sandbox` reserved), a plugin is a directory with a manifest, config is an install list. Deliberately *not* the custom-element/`window.sideview` shape first — HTML as a file earns its place before a component layer does, and same-origin trust means the API needs no plumbing when it arrives. *(pulled 2026-08-09, thread 30)*
- **html blocks as Vue islands — lean in** — the vendoring and CORS shipped in v2; v3 delivered the rest of the prize (2026-08-10, thread 39): an **import map in the iframe prelude**, so a block writes `import { createApp, ref } from 'vue'` — the spelling every model knows — instead of a vendored path it must be told; the skill teaches the pattern with its caveats (composition API with explicit `setup()`, no `<script setup>` sugar without a compiler; islands cannot reach the page); and `examples/vue-island.sv` is the worked example, live and interactive. *(pulled 2026-08-09, thread 31)*
- **Binary releases + AUR** — tag-triggered GitHub releases with prebuilt per-target archives, checksums and deb/rpm (the sqlnow shape — its release.yml is the template; sideview is pure Rust with embedded assets, so it can go simpler, and musl/static is on the table since nothing dlopens), plus an AUR package. `cargo install` stops being the only door. *(author, 2026-08-09, chat)*
- **Three page formats, and a repo config** — `.md` and `.html` become page formats sideview accepts and tracks, not new block types (author, 2026-08-10). Design in the formats section below; it replaces the md→sv conversion, so the docs stay markdown and GitHub keeps rendering them.
- **Page management at scale** — a project with many pages outgrows the chip strip: each `<sv-page>` may declare a `category` (canon, beside `order` — for committed pages, grouping is plan-worthy so it lives in the file), imported pages get theirs from `.sideview.toml`, and **the strip carries one category's pages and nothing else** (author, 2026-08-10). Its length is the whole point: a project may hold dozens of pages, but you work inside one set at a time, so the strip shows that set behind a title naming it — never a category chip, since listing categories in the strip is the length problem again. The title names the set and nothing more. The wordmark opens **`/home`** — every category with its pages, the untitled set leading — and that is the *only* place categories are browsed: per-category pages were built, tried and scrapped the same day. A project with no categories never sees any of it: home is then the view that existed before them, every page in the strip. **Built and dogfooded 2026-08-10**: this project's own eleven pages now live in four categories, its docs still markdown. *(pulled 2026-08-09, thread 32)*
</sv-prose>

<sv-prose id="goal">
## Comment attachments — the little plan

- **Any file, not just images** (author, 2026-08-09): the mechanics never cared — paste or drop into the compose card, the daemon writes the file, the comment references it. Images are the first-class case: thumbnail in the card, full size on click. Everything else wears a file chip — name, size, type — opening through `/f/`.
- **Three homes, split by lifetime — the placement principle applied to files** (author, 2026-08-09). *Comment* attachments live in `.sideview/attachments/<sha8>/<original-name>` — project-local (the sandbox law), self-gitignored, conversation's lifetime: if the db goes, they are fair game. A *throwaway page's* images live beside their page, `.sideview/pages/<session>/` — the page's lifetime: `page rm` takes the directory with the file, `page promote` moves it into the repo and re-points references. A *committed document's* files live in the repo proper, beside what references them, git's and untouchable — nothing that happens to the db or the conversation may ever threaten them. **The attachments folder takes writes from the comment upload alone** — a page's images never land there, whatever the page's tier; "add it to the document" copies *out* of conversation storage into the page's own home, the same crossing as promote.
- **The channel**: the page POSTs the raw bytes to a new `/api/attachments` (filename in the query — no multipart machinery to parse), which writes the file and returns its path and hash; sending the comment binds them as rows in an `attachments` table. **Metadata in the db, bytes on disk** (author, 2026-08-09): the card, the gc and "what references this" stay one query, while the file stays where every agent's own tools — including vision — read it directly. Blobs-in-db considered and rejected by the author the same day: they'd bloat the store, lengthen write transactions, and put an extraction step between the agent and the file. A canceled draft's upload is just an unreferenced file; gc collects it. An additive migration, priced with 0.3. Same trust line as comments: the page authors conversation, never canon.
- **Watch events name the paths.** The agent reads an image with its own file tool — genuine vision, pull not push, the founding thesis — and any other file the same way. The skill grows a line.
- **Lifecycle** (author, 2026-08-09): deletion follows the document — `page rm` cascades threads, comments, and their attachments with them. Everything else is a deliberate verb, never a daemon habit: `sideview attachments gc` deletes only files nothing references, checked against live conversation *and* every current page's content, and reports what it took (a startup auto-sweep was considered and dropped — after the resurrection test it would silently take everything). `--resolved` widens it to attachments held only by resolved threads, for repos where they pile up; explicitly not the default — resolved conversation is folded, not gone. **gc's writ runs only inside `.sideview/attachments/`** — committed document assets are git's, untouchable by construction; and a page found referencing conversation storage is protected but *reported* as mis-homed ("promote this file"), because the page-content check is a backstop for that mistake, not a place to keep canon.
- **Limits, honest and few**: a size cap, a sanitized filename, a sniffed content type. Nothing executes; `/f/`'s root confinement and its `.sideview` exclusions already apply.
- **Build order** (author, 2026-08-09): backend first — table, upload, gc, watch payloads — then the comment UI rebuilt around them; the card redesign and the resizable bar land as that one pass.
- **Inline placement, plain textarea** — paste/drop inserts a markdown-shaped token at the cursor (`![name](att:<sha8>)`); the card renders the thumbnail where the token sits; the watch body keeps the token, so the agent knows *which* image "this one" is when several ride one comment. Multiple attachments per comment stay allowed — a one-attachment cap was considered and declined (it scatters one thought across cards to solve an ambiguity the tokens already solve). No contentEditable, no rich-text editor.
- **Vim motions in the compose box** — an option, off by default, a viewer preference. The credible route is CodeMirror 6 vendored as a maintainer-built bundle (rung-1 precedent: maintainer-time toolchain, one-binary promise intact), vim keymap lazy-loaded. Priced honestly at a few hundred KB of vendor weight; decided at the *end* of the compose rebuild, when the textarea's limits are felt rather than guessed — it's an additive swap, not a foundation.
- Ships with the comment-card redesign and the resizable bar, per the In list.

**Migration v3** — the model, for review before a line is written:

```sql
CREATE TABLE attachments (
    id         INTEGER PRIMARY KEY,
    comment_id INTEGER NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
                                  -- rows are born when the comment is sent, never
                                  -- at upload: a canceled draft leaves only an
                                  -- unreferenced file for gc, not a dangling row
    path       TEXT NOT NULL,     -- project-relative: .sideview/attachments/<sha8>/<name>
    name       TEXT NOT NULL,     -- original filename, sanitized; kept for the agent's sake
    mime       TEXT NOT NULL,     -- sniffed at upload, never trusted from the client
    bytes      INTEGER NOT NULL,  -- the cap is enforced at upload, recorded here
    sha256     TEXT NOT NULL,     -- integrity and the dedupe key: same bytes, one file
    created_at INTEGER NOT NULL
);
CREATE INDEX attachments_by_comment ON attachments(comment_id);
CREATE INDEX attachments_by_sha    ON attachments(sha256);
-- the FK cascade clears rows when conversation goes (page rm); the daemon deletes
-- the files it queried first — SQL cannot unlink from disk, and gc backstops it.
-- Watch events carry the whole row (path, name, mime, bytes), not just a path.
```

## Three page formats, and `.sideview.toml`

- **Formats, not block types** (author, 2026-08-10). A page is a file; sideview knows three. `.sv` stays the *composed* format — typed blocks, interleaved diffs and (later) tables. `.md` and `.html` are *imported* formats: rendered whole, one block per file, through the paths that already exist. No format change, no new tag, no new thing for the skill to teach — the limitations attach to the format, where a reader looks for them.
- **What you get, stated plainly.** Markdown and inline HTML render into the page and are **fully commentable** — anchors are heading ids and paragraph hashes computed from the *rendered* text, which never cared where the text came from. A full HTML document that wants its own world is iframed instead, and there commenting stops at the block: the page cannot reach into a sandboxed frame (V0's rule, unchanged). Inline HTML runs its own CSS and JS in our page — the same trust story as markup blocks, and the same caveat: body-level layout will fight the chrome.
- **One block per file, deliberately.** Splitting a doc at its headings would give surgical patches but make block ids heading-derived — and block ids are what comments target, so renaming a heading would orphan every thread under it. One block keeps paragraph anchors surviving everything except an edit to their own paragraph; the whole-file re-render is absorbed by the reading anchor today and fixed properly by patch-in-place morphing later.
- **`.sideview.toml` at the repo root — TOML, committed, agent-authored** (author, 2026-08-10; no CLI writer, since agents edit files trivially and the one-author rule stays intact). Root, not inside `.sideview/`: that directory self-ignores with a single `*` and holds disposable machinery, while config is versioned intent — the placement principle, applied to a config file.
- **It supplies only what a file cannot say about itself.** An `.sv` page declares its own label, order and category in canon. Markdown and HTML have nowhere to put attributes, so config is their only voice: `[[pages]]` with `path`, `category`, optional `label`/`order`, and `render = "inline" | "iframe"` for HTML. Precedence follows: the file wins for anything it can express, config fills the rest.
- **Config is what survives the db.** Entries are re-applied at startup, so the resurrection test brings imported pages back too — `.sv` files announce themselves in the scan, markdown never does, and sideview must not colonize a repo's markdown by scanning for it. `port` joins it for the same reason: V2's own sign-off recorded that the remembered port dies with the db, and durability of that kind belongs in configuration.
- **Deletion splits by tier, not by format** (author, 2026-08-10, sharpening it): a throwaway page under `.sideview/pages/` is sideview's own scratch and `rm` means rm; **anything in the repo — a promoted `.sv` as much as an imported `DESIGN.md` — is unbound and left on disk**, because it is a committed file and should be exactly as scary to delete as any other. The page's ✕ never deletes canon; `page rm <id> --file` is the deliberate second word, and git is the other answer.
- **A bad config never costs you the page**: log it, report it in `status`, serve without it. And note for the docs: a worktree's store resolves to the main checkout, so the daemon reads that copy of the config.

## Plugins — the design

- **Registration is the trust act** (author, 2026-08-10, and the model is VS Code's, not the web's). An extension listed in config is an *install*: fully trusted, same-origin, may reach a CDN, may call the page's own endpoints. Agent-authored `sv-html` is *content*: `srcdoc`, sandboxed, envelope-only. Nobody has to reason case by case — you either installed it or you didn't. The `sandbox` attribute was never buying security for code you installed on purpose.
- **The type is the extension's declaration, never the installer's choice** (author, 2026-08-10, correcting the reverse). With trust settled, the mode decides only what the plugin's CSS and JS are *written against*, and only its author knows that: an inline plugin authored against Bootstrap and the tokens would look broken alone in a frame; a framed one with its own reset would trample the page. They are different artifacts, so the manifest says which.
  - **`inline`** — renders into the page; inherits Bootstrap, the tokens and the theme; **commentable with no new machinery**, since its text hashes like any other. Its CSS is global in both directions — the price of sharing the chrome. Relative asset references are rewritten to the plugin's own directory, because the manifest names it and `./style.css` should mean what the author obviously meant.
  - **`frame`** — its own CSS and JS in a same-origin iframe served from `/f/`: isolated *styling*, not isolated trust. The parent can measure it directly (no sizing handshake) and can walk its DOM, so **comments work here too**.
  - **`sandbox`** — **reserved, deliberately not built** (author, 2026-08-10): an opaque-origin frame for embedding a foreign app — an Observable widget, someone else's bundle — where the extension wants no access and is granted none. Space is left in the vocabulary because the machinery is already the content path; comments there would need the plugin to post `{sv: 1, type: "comment", …}` itself, which makes commenting a capability a plugin *offers* rather than one the host takes.
- **A plugin is a directory with a manifest.** `extensions/<name>/plugin.toml` — `name`, `type`, `entry`, `version` — beside its html, css, js and assets, served through `/f/` under the confinement that already exists. Required, not inferred from a stray `index.html`: the manifest is what makes an install deliberate, and it follows the standing rule that config supplies only what an artifact cannot say about itself.
- **`.sideview.toml` shrinks to an install list** — a path, whether it is enabled, and whatever the *project* decides that the plugin cannot.
- **Degradation is envelope-first**, as everywhere else: an unknown `type`, or a manifest `version` above what this daemon knows, renders an honest "this sideview doesn't know…" note rather than guessing.
- **The other plugin kinds, named and not built**: *block plugins* (a custom element claiming `sv-<tag>`, the daemon passing the body through instead of degrading it) · *subprocess plugins* (a command whose stdout is rendered — DESIGN.md's "a command, its streams, an optional port") · *chrome plugins* (rail lenses, header controls, the `window.sideview` API — the only kind that can break the page, and same-origin trust means it needs no `postMessage` plumbing when it comes).
- **First step, and only that**: HTML as a file in both built types, registered, with the commenting that falls out. Distribution from outside the repo — npm, crates, a URL, SRI — stays a separate decision.

**Binary extensions — the LSP-shaped route** (author, 2026-08-10; design only, a v3-plus-one build):

- **Two axes, not one** — the author's binary idea exposed a conflation in the types above: how a plugin's HTML is *produced* and how it is *hosted* are independent. The manifest wants `source = "file" | "command"` (later `"process"`) beside `render = "inline" | "frame" | "sandbox"`. A binary's output can be hosted any of the three ways.
- **The convention is sideview's own**: an extension declares a tag, a block reads `<sv-sqlnow>select … from readings</sv-sqlnow>`, and the daemon runs the binary with **the body on stdin** and attributes as flags — no argument quoting to get wrong. stdout is the block. This is a better *first* block plugin than the custom-element sketch, because rendering stays server-side where all other rendering lives, and it is `{sql}` finally exercising reference-never-embed: the spec holds a query, the rows reach the page without passing through any model's context.
- **Four rungs, and the second is the interesting one.** (1) *Exec per render* — block changes, run, done; enough for a table in a plan. (2) **Streaming exec** — the author's instinct, and simpler than it sounds rather than harder: the same one-shot child, its stdout consumed as it arrives, ending when the process does. In `frame`/`sandbox` mode this is **free and needs no protocol at all** — the daemon serves `/x/<ext>` as a chunked response and the browser paints rows as they stream, which is how HTML worked before anyone invented a client; inline mode has no such luxury and would need an append event kind. (3) *Exec per request* — the page POSTs arguments to `/x/<ext>` for sort, page, drill; that endpoint exists already for rung 2. (4) *A persistent stdio child* speaking JSON lines — LSP proper, for a warm connection across many queries.
- **Startup cost is priced and accepted** (author, 2026-08-10): a Rust binary starts in nothing, and while DuckDB opening a database and loading extensions is real, nobody is waiting on it — you have been waiting on the model far longer. So rung 4 exists for *streaming and repeated interaction*, not for latency, which reorders the ladder honestly.
- **Caps and honesty, specified rather than discovered**: a timeout and an output-size cap (a runaway query must not hang the poll loop or push half a gigabyte into a page), stderr to `daemon.log` with a visible error block on non-zero exit rather than a silent gap, cwd at the project root, and a re-run policy that is *never* every poll tick — re-run on a change to the block's body or attributes, plus an explicit refresh and any input globs the extension declares.
- **Engine and view are separable, which is what settled the table** (author, 2026-08-10): a binary or child process is an *engine*, a page or island is a *view*, and they meet at `/x/<ext>`. That is why nothing needs forking — sqlnow can supply both sides while sideview supplies neither, and any other engine can take the same place later.
- **Two manifest fields**: `output = "html" | "markdown"` — a binary that already speaks markdown should not have to learn HTML, and markdown lands in the path comrak and the prose layer already own — and **argv templating from block attributes**, `args = ["--rpc", "{db}"]`, run as an argv array with **no shell**, each placeholder becoming exactly one argument. Same lesson as choosing gitoxide over `git`: never build a command line out of strings someone else can influence.
- **Measured while considering a duckdb-CLI table and kept as general guidance** (2026-08-10; the CLI route itself is *not* taken — see the table entry): a binary's *aligned* output buffers by construction (duckdb's `-markdown` took 1.6s to first byte on 5M rows, since column widths need the whole result) while its *line-oriented* output streams from the first millisecond (`-jsonlines`, `-csv`: 11ms). Process start is a non-issue — 11ms cold, 37ms for a million-row aggregate. So an extension that must stream should emit lines, and one that must align should not pretend to stream.
- **The table extension is the big case only** (author, 2026-08-10). A few dozen rows are not a feature: an agent runs whatever tool it has — sqlnow's CLI, duckdb's, anything — and pipes a markdown table into a prose block, which works today and adds no dependency to anything. **Anything bigger than the screen is a widget, not a rendering**: fixed header, windowed rendering (paint what is visible, not 50,000 rows of DOM), resizable columns, client-side sort. So the extension targets that and only that, and **it does not depend on the duckdb binary** — sqlnow embeds its engine, which was part of its own design.
- **Which makes the persistent stdio child the primary target, not the endpoint.** A virtualized grid cannot consume a stream; it asks questions — the schema, *rows 5,000–5,100 sorted by column three*, how many rows there are, and cancel that because the user kept scrolling. So the protocol is request/response with ids and cancellation over one long-lived child: LSP's actual shape rather than its aesthetic, carrying a **window** rather than a row.
- **The protocol is ours; the grid and the engine are sqlnow's.** A `frame`-mode extension serves sqlnow's own UI from its own files, and that frame — same-origin — fetches `/x/<ext>`, which the daemon **relays** to the child over pipes. sideview writes a relay and a protocol and no grid at all, which is how a properly-considered table widget gets built without us building it. Keeping the protocol general is the LSP lesson proper: sqlnow is the first implementation, never the definition, so a duckdb adapter or anything else may speak it later.
- **Child lifecycle**: spawned on first request, **one per block** (each holds its own connection), kept while a viewer is attached, reaped after idle, killed with the daemon — which is the reaping DESIGN.md already promised, arriving through pipes instead of ports.
- **The honest cost**: every scroll is browser → daemon → child → engine and back. Locally that is milliseconds plus query time, and prefetching the adjacent window hides it; but it is the reason the protocol windows rather than rows.
- **A quiet consequence**: a persistent stdio child *is* "supervise → endpoint" without ports or namespaces, since the daemon runs on the host and talks over pipes. The service-block thesis gets a first version that never needed the spike.

## The comment UI around attachments

- **Mobile: the open bar is the page** (author, 2026-08-09, from the phone: the bar is already as wide as it can realistically be — so stop pretending). Two states, folded-to-chip and full-screen sheet: the sheet covers the header and chip menu, the document beneath stops being drawn, the body is locked at its reading position, and a thumb-sized × in the title row is the way out. **Built and lived in the same day** — the seven platform causes it took are in HANDOFF, and its shape is now structural (title row above a scrolling sibling, sheet pinned to the *visual* viewport so the keyboard never buries the compose box). Desktop keeps the side bar, and drag-to-resize arrives with it.
- **Compose**: paste or drop into any compose box — draft or reply — uploads immediately and inserts the token at the cursor (`![name](att:<sha8>)`); a chip row under the box shows what rides the comment, with remove. Every upload attaches whether or not its token survives editing; tokens control *placement*, not membership.
- **Cards**: image tokens render as thumbnails where they sit, tap for full size through `/f/`; non-image attachments wear a file chip — name, size — tap to open. Attachments without a token trail the body.
- **Bodies graduated to markdown on day one** (author, 2026-08-09 — raw tokens sitting in sent cards made the case the plan predicted): rendered server-side by the same comrak pass as everything, in *safe* mode — raw HTML escaped, never omitted, because a comment comes from whoever can see the page — with `att:` images resolving against the comment's own rows. The compose box stays raw text, preview-on-send; inline WYSIWYG remains the CodeMirror question, decided at the end of this pass.

## Goal — blessed by the author, 2026-08-09 (thread 33)

v3 is done when every item on the In list above is accepted by the author — through this page's own machinery — and **0.3.0 is on crates.io**.
</sv-prose>

</sv-page>
